package: awnav
version: '0.3.1'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/aw_navigation

page:
    title: 'translate:awnav'
    icon: rex-icon fa-bars


requires:
    redaxo: '>=5.0.0'
